#!/bin/bash
set -euo pipefail

BINARY=opt-eikana
BINARY_DIR=/usr/local/bin
PLIST=2754github.opt-eikana.plist
PLIST_DIR=/Library/LaunchDaemons

sudo launchctl unload $PLIST_DIR/$PLIST 2>/dev/null || true
sudo rm -f $PLIST_DIR/$PLIST
sudo rm -f $BINARY_DIR/$BINARY

echo ''
echo "「システム設定 > プライバシーとセキュリティ > アクセシビリティ」から $BINARY を削除してください。"
